// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_YEaAYBNwsfvP8dgw0t4N2oPAhTSDcho',
    appId: '1:572346824544:web:dabb2f41feb6d1aacc9005',
    messagingSenderId: '572346824544',
    projectId: 'smartstack-5bb46',
    authDomain: 'smartstack-5bb46.firebaseapp.com',
    storageBucket: 'smartstack-5bb46.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABHGXBIUbD0ImWbFQ180IxxkhRCEVDtH8',
    appId: '1:572346824544:android:4bcfdfae666bd4f6cc9005',
    messagingSenderId: '572346824544',
    projectId: 'smartstack-5bb46',
    storageBucket: 'smartstack-5bb46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC66E07PgK8Up71xk-i1k8tRb44rfWLk6M',
    appId: '1:572346824544:ios:440d5fe05e4cbfc2cc9005',
    messagingSenderId: '572346824544',
    projectId: 'smartstack-5bb46',
    storageBucket: 'smartstack-5bb46.firebasestorage.app',
    iosBundleId: 'com.example.smartstackApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC66E07PgK8Up71xk-i1k8tRb44rfWLk6M',
    appId: '1:572346824544:ios:440d5fe05e4cbfc2cc9005',
    messagingSenderId: '572346824544',
    projectId: 'smartstack-5bb46',
    storageBucket: 'smartstack-5bb46.firebasestorage.app',
    iosBundleId: 'com.example.smartstackApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_YEaAYBNwsfvP8dgw0t4N2oPAhTSDcho',
    appId: '1:572346824544:web:9b9e3c6f9a02d3a7cc9005',
    messagingSenderId: '572346824544',
    projectId: 'smartstack-5bb46',
    authDomain: 'smartstack-5bb46.firebaseapp.com',
    storageBucket: 'smartstack-5bb46.firebasestorage.app',
  );
}
